name: Docker

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache resources
        id: cache-resources
        uses: actions/cache@v4
        with:
          path: resource_dir
          key: ${{ runner.os }}-resource_dir-${{ hashFiles('resource_dir/**') }}
      
      - name: Download resources
        if: steps.cache-resources.outputs.cache-hit != 'true'
        run: |
          mkdir -p resource_dir
          aws s3 sync s3://igm-public-dropbox/snvstory/resource_dir/ ./resource_dir/ --no-sign-request

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/MHH-Humangenetik/snvstory            

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}